<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TarkovHelper.Core\TarkovHelper.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp.Views.WPF" Version="4.151.1" />
    <PackageReference Include="Svg.Skia" Version="5.2.0" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260627" />
    <PackageReference Include="ScreenCapture.NET" Version="3.0.0" />
    <PackageReference Include="ScreenCapture.NET.DX11" Version="3.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <None Include="tessdata\eng.traineddata" CopyToOutputDirectory="PreserveNewest" />
    <None Include="icons\manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="icons\images\**\*.webp" CopyToOutputDirectory="PreserveNewest" LinkBase="icons\images" />
  </ItemGroup>

</Project>
